export const CATEGORIES = [
  'Productivity',
  'Engineering & Development',
  'Design & Creative',
  'Finance',
  'Social & Community',
  'Marketing & Sales',
  'Health & Fitness',
  'Travel',
  'Platforms',
  'Product add-ons',
  'AI Agents',
  'Web3',
  'LLMs',
  'Physical Products',
  'Voice AI Tools',
  'Ecommerce',
  'No-code Platforms',
  'Data analysis tools',
] as const;

export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    description: 'Basic listing',
    features: {
      listing: true,
      socialPromotion: false,
      newsletter: false,
      chooseDate: false,
      badge: false,
    },
    highlight: false,
    badge: null,
  },
  {
    id: 'join',
    name: 'Lite',
    price: 9,
    description: 'Social boost',
    features: {
      listing: true,
      socialPromotion: true,
      newsletter: false,
      chooseDate: false,
      badge: true,
    },
    highlight: false,
    badge: null,
  },
  {
    id: 'skip',
    name: 'Pro',
    price: 39,
    description: 'Full promotion',
    features: {
      listing: true,
      socialPromotion: true,
      newsletter: true,
      chooseDate: true,
      badge: true,
    },
    highlight: true,
    badge: 'Most Popular',
  },
  {
    id: 'grow',
    name: 'Grow',
    price: 199,
    description: 'Pro + directory submissions',
    features: {
      listing: true,
      socialPromotion: true,
      newsletter: true,
      chooseDate: true,
      badge: true,
    },
    highlight: true,
    badge: 'Most Impact',
  },
  {
    id: 'relaunch',
    name: 'Relaunch',
    price: 19,
    description: 'Second chance',
    features: {
      listing: true,
      socialPromotion: true,
      newsletter: true,
      chooseDate: false,
      badge: true,
    },
    highlight: false,
    badge: null,
  },
] as const;

export const PLAN_FEATURE_LABELS = {
  listing: 'Listed on Launch homepage',
  socialPromotion: 'Promoted on X & LinkedIn',
  newsletter: 'Featured in newsletter (2K+ subs)',
  chooseDate: 'Choose your launch date',
  badge: 'Verified badge for your site',
} as const;
