project_id = "gzpypxgdkxdynovploxn"

[functions.subscribe-to-newsletter]
verify_jwt = false

[functions.send-submission-email]
verify_jwt = false

[functions.enrich-product]
verify_jwt = false

[functions.post-to-x]
verify_jwt = false


