project_id = "gzpypxgdkxdynovploxn"

[functions.vibecodedit-newsletter]
verify_jwt = false

[functions.send-submission-email]
verify_jwt = false

[functions.enrich-product]
verify_jwt = false

[functions.post-to-x]
verify_jwt = false



[functions.og-share]
verify_jwt = false
